apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: filebeat-coralogix-daemonset
  namespace: kube-system
  labels:
    k8s-app: filebeat-coralogix-logger
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: filebeat-coralogix-logger
  template:
    metadata:
      labels:
        k8s-app: filebeat-coralogix-logger
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: filebeat-coralogix-service-account
      terminationGracePeriodSeconds: 30
      containers:
      - name: filebeat-coralogix
        image: docker.elastic.co/beats/filebeat:6.7.0
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
        envFrom:
        - secretRef:
           name: filebeat-coralogix-account-secrets
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: filebeat-http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /stats
            port: filebeat-http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        ports:
        - name: filebeat-http
          containerPort: 5066
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
          readOnly: true
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlog
          mountPath: /var/log
        - name: log
          mountPath: /var/log/filebeat
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: coralogix-certificate
          mountPath: /coralogix/certs/ca.crt
          subPath: ca.crt
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: filebeat-coralogix-config
          defaultMode: 0600
      - name: data
        hostPath:
          path: /var/lib/filebeat
          type: DirectoryOrCreate
      - name: log
        hostPath:
          path: /var/log/filebeat
          type: DirectoryOrCreate
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: coralogix-certificate
        secret:
          secretName: filebeat-coralogix-certificate
