kind: ConfigMap
apiVersion: v1
metadata:
  name: filebeat-config
data:
  filebeat.yml: |-
    name: filebeat-coralogix
    tags: ["kubernetes", "containers"]
  
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true

    http:
      enabled: true
      host: "0.0.0.0"
      port: 5066

    processors:
    - drop_event:
        when:
          equals:
            kubernetes.container.name: "filebeat-coralogix"
    - add_cloud_metadata: ~
    - decode_json_fields:
        fields: ["message"]
        process_array: true
        max_depth: 3
        target: "message"
        overwrite_keys: true
    - add_fields:
        target: ''
        fields:
          cluster_name: ${CLUSTER_NAME:cluster.local}
    - copy_fields:
        fields:
        - from: kubernetes.namespace
          to: APP_NAME
        - from: kubernetes.container.name
          to: SUB_SYSTEM
        - from: kubernetes.node.hostname
          to: beat.hostname
        - from: container.id
          to: kubernetes.container.id
        fail_on_error: false
        ignore_missing: true
    - rename:
        fields:
         - from: kubernetes.labels
           to: kubernetes.pod.labels
        fail_on_error: false
        ignore_missing: true
    - drop_fields:
        ignore_missing: true
        fields:
        - agent
        - ecs
        - container
        - source
        - log
        - input
        - prospector
        - host
        - stream
        - offset
        - kubernetes.namespace_uid
        - kubernetes.namespace_labels
        - kubernetes.node.uid
        - kubernetes.pod.uid
        - kubernetes.replicaset

    fields_under_root: true
    fields:
      PRIVATE_KEY: '${PRIVATE_KEY:?Private key is required but not specified!}'
      COMPANY_ID: '${COMPANY_ID:?Company ID is required but not specified!}'

    logging:
      level: info
      to_files: true
      files:
        path: /var/log/filebeat
        name: filebeat.log
        keepfiles: 7
        permissions: 0644

    output.logstash:
      enabled: true
      hosts: ["logstashserver.coralogix.com:5015"]
      tls.certificate_authorities: ["/coralogix/certs/ca.crt"]
      ssl.certificate_authorities: ["/coralogix/certs/ca.crt"]
