apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat-coralogix-service-account
  namespace: kube-system
  labels:
    k8s-app: filebeat-coralogix-logger
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: filebeat-coralogix-service-account-role
  namespace: kube-system
  labels:
    k8s-app: filebeat-coralogix-logger
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: filebeat-coralogix-service-account
  namespace: kube-system
  labels:
    k8s-app: filebeat-coralogix-logger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: filebeat-coralogix-service-account-role
subjects:
- kind: ServiceAccount
  name: filebeat-coralogix-service-account
  namespace: kube-system
