kind: ConfigMap
apiVersion: v1
metadata:
  name: fluent-bit-coralogix-config
  namespace: kube-system
  labels:
    k8s-app: fluent-bit-coralogix-logger
data:
  fluent-bit.conf: |-
    [SERVICE]
        Flush         1
        Daemon        Off
        Log_Level     warning
        HTTP_Server   On
        Parsers_File  parsers.conf

    [INPUT]
        Name                tail
        Tag                 kube.*
        Path                /var/log/containers/*.log
        DB                  /var/log/flb_kube.db
        Parser              docker
        Mem_Buf_Limit       5MB
        Refresh_Interval    10

    [FILTER]
        Name                kubernetes
        Match               *
        Merge_Log           On
        Merge_Log_Key       log
        K8S-Logging.Exclude On

    [FILTER]
        Name    lua
        Match   *
        script  /fluent-bit/etc/functions.lua
        call    dedot

    [FILTER]
        Name            nest
        Match           *
        Operation       lift
        Nested_under    kubernetes
        Add_prefix      kubernetes.

    [FILTER]
        Name    modify
        Match   *
        Copy    kubernetes.namespace_name applicationName
        Copy    kubernetes.container_name subsystemName
        Copy    kubernetes.host computerName
        Remove  kubernetes.container_hash
        Remove  kubernetes.docker_id
        Remove  kubernetes.pod_id

    [FILTER]
        Name            nest
        Match           *
        Operation       nest
        Wildcard        kubernetes.*
        Nest_under      kubernetes
        Remove_prefix   kubernetes.

    [FILTER]
        Name        nest
        Match       *
        Operation   nest
        Wildcard    kubernetes
        Wildcard    log
        Wildcard    time
        Wildcard    stream
        Nest_under  json

    [OUTPUT]
        Name            http
        Match           *
        Host            ${CORALOGIX_API_URL}
        Port            443
        URI             /logs/rest/singles
        Format          json_lines
        JSON_Date_Key   timestamp
        Compress        On
        TLS             On
        Header          private_key ${PRIVATE_KEY}
        Header          coralogix-timeunit seconds
        Retry_Limit     5
